FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY build.gradle.kts settings.gradle.kts gradlew ./
COPY gradle ./gradle

RUN chmod +x gradlew

COPY src ./src

RUN ./gradlew clean build -x test

FROM eclipse-temurin:21-jdk
WORKDIR /app

RUN apt-get update && apt-get install -y graphviz && apt-get clean

COPY --from=builder /app/build/libs/*.jar app.jar

RUN groupadd spring && useradd -g spring -m -s /bin/bash spring
RUN chown -R spring:spring /app
USER spring

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
