spring.application.name=nltouml

openai.api.key=${OPENAI_API_KEY}
openai.model.name=${OPENAI_MODEL_NAME}

gemini.api.key=${GEMINI_API_KEY}
gemini.model.name=${GEMINI_MODEL_NAME}

deepseek.api.key=${DEEPSEEK_API_KEY}

logging.level.com.group15.nltouml=trace
